- src/App.tsx
- src/components/pages/GameContainer/Game/Lobby.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- URL populates with a sharable link on joining/creating a game
- Going to a shared URL automatically joins a game if the lobby exists
Future:
Need to add a copy-to-clipboard button to easily copy the URL for sharing
> Sharable URL to invite to game

- src/api/apiRequests.tsx
- src/components/pages/GameContainer/Game/Pregame.tsx
- src/components/pages/GameContainer/gameTypes.ts
- Add API call to get 3 words at a time
- Add useEffect to Pregame component to get words on loading
- Add button to get 3 new word suggestions
> Replace dummy word suggestions in Pregame phase with words from API call

- src/components/pages/GameContainer/GameContainer.tsx
- Automatically store and get username from localStorage to keep username between games.
> Add localStorage get/set username. Add, move comments.

- src/components/common/Host/Host.tsx
- src/components/common/Player/Player.tsx
- src/components/common/PlayerList/PlayerList.tsx
- src/components/common/PlayerList/index.ts
- src/components/common/SetHost/SetHost.tsx
- src/components/common/SetHost/index.ts
- src/components/common/Timer/Timer.tsx
- src/components/pages/GameContainer/Game/Postgame.tsx
- src/components/pages/GameContainer/Game/Pregame.tsx
- src/components/pages/GameContainer/Game/Writing.tsx
- src/components/pages/GameContainer/Game/index.ts
- src/components/pages/GameContainer/GameContainer.tsx
- src/state/index.ts
- src/state/isHostState.ts
- src/state/lobbyState.ts
- src/state/playerIdState.ts
- src/styles/general.scss
- src/types/gameTypes.ts
- Add SetHost component to allow Host to pick a new Host
- Add input for Host to choose timer length
- Update Timer to get seconds from lobbyData.settings
- Add Host back into PlayerList
- Remove isHost atom, get from lobbyData instead
- Update styling
> Update host settings. Add Timer settings. Add SetHost component.

- src/components/common/PlayerList/PlayerList.tsx
- src/components/pages/GameContainer/GameContainer.tsx
Remove playerId prop from PlayerList. Subscribe PlayerList to playerId atom.
> Remove playerId prop from PlayerList.

- src/components/pages/GameContainer/Game/Lobby.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- Add simple username length validation and trimming (2 - 12 characters)
- Remove console.log lobbyData
> Add simple username length validation and trimming

- src/components/pages/GameContainer/Game/Lobby.tsx
- src/components/pages/GameContainer/Game/Pregame.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- src/styles/components/pages/Lobby.scss
- src/styles/components/pages/Pregame.scss
- src/styles/gameContainer.scss
- src/styles/general.scss
- src/styles/globals.scss
> updated styles

- src/components/common/Modal/Modal.tsx
- src/components/common/Modal/index.ts
- src/components/pages/GameContainer/Game/Guessing.tsx
- src/components/pages/GameContainer/Game/Writing.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- Add Modal component
- Implement confirmation Modal on Writing phase to pop up when the timer is still running
- Implement confirmation Modal on Guessing phase to pop up when any players are missing a guess
> Add confirmation Modal component

- src/components/pages/GameContainer/GameContainer.tsx
- src/hooks/useLocalStorage.ts
this hook reads/writes to local storage.
> useLocalStorage hook

- src/components/common/PlayerList/PlayerList.tsx
- src/components/common/Timer/Timer.tsx
- src/components/pages/GameContainer/Game/Guessing.tsx
- src/components/pages/GameContainer/Game/Postgame.tsx
- src/components/pages/GameContainer/Game/Pregame.tsx
- src/components/pages/GameContainer/Game/Writing.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- src/styles/components/common/cookiePopup.scss
- src/styles/components/pages/Pregame.scss
- src/styles/general.scss
- src/styles/globals.scss
Writing stage complete sans module.
> Style system

- src/components/pages/GameContainer/Game/Guessing.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- Add more robust leave-game functionality with confirmation Modal
- Add 'game rejoin' socket listener to give player the option to rejoin rather than it being automatic
- Add 'player guess' socket listener and emitter to make Host send each player their guess number
> Add ability to leave, rejoin game with Modals. Add guess number messaging

- src/components/common/SetHost/SetHost.tsx
- src/components/pages/GameContainer/Game/Postgame.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- src/hooks/useLocalStorage.ts
- Add host sends guesses array to new host on 'set host' event
- Add new host receives guesses array from previous host and sets to state
- Add updateValue function to useLocalStorage hook that will read data from localStorage and update state for when the localStorage value has changed via another hook or other means
> Fix new host not seeing the results correctly due to missing host-generated data

- src/components/common/SetHost/SetHost.tsx
- src/components/pages/GameContainer/Game/Guessing.tsx
- src/components/pages/GameContainer/Game/Pregame.tsx
- src/types/gameTypes.ts
- src/utils/constants.ts
- src/utils/helpers/gameHelpers.ts
- Add constants/.env variables
- Add helper functions to determine if there are enough players to start the game and display UI differences
- Add dropdown selection in Guessing phase for large games
- Disable Start Game button on Pregame if minimum players not met
- Fix SetHost working when there aren't enough players
- Add minor refactors and cleanup
> Add logic for minimum players and large game breakpoint.

- src/components/pages/GameContainer/Game/Pregame.tsx
- src/components/pages/GameContainer/Game/Writing.tsx
- Simplify showEditName conditional checking
- Add autoFocus to Edit Name input
- Add autoFocus to definition input
> Add autoFocus to inputs

- src/App.tsx
- src/components/common/Footer/Footer.tsx
- src/components/common/Footer/index.ts
- src/styles/components/common/footer.scss
- src/styles/gameContainer.scss
- src/styles/general.scss
- src/styles/globals.scss
- src/styles/index.scss
- Add Footer component with link to Story Squad
- Add email subscription form (no functionality yet)
- Add basic styling for footer and update other styles as needed
> Add Footer with basic styling

- src/components/common/CharCounter/CharCounter.tsx
- src/components/common/CharCounter/README.md
- src/components/common/CharCounter/index.ts
- src/components/pages/GameContainer/Game/Guessing.tsx
- src/components/pages/GameContainer/Game/Lobby.tsx
- src/components/pages/GameContainer/Game/Writing.tsx
- src/styles/components/common/charCounter.scss
- src/styles/globals.scss
- src/styles/index.scss
- src/utils/constants.ts
- src/utils/validation/definitionValidation.ts
- src/utils/validation/userNameValidation.ts
- Add CharCounter component
- Implement CharCounter on inputs and textarea
- Add styling to CharCounter and wrapper div
- Update validation requirements
- Add constants
> Add character counter to inputs and textarea

- package.json
- src/components/common/EmailInput/EmailInput.tsx
- src/components/common/EmailInput/index.ts
- src/components/common/Footer/Footer.tsx
- typings.d.ts
- yarn.lock
Convertkit-react library docs [here](https://github.com/ConvertKit/convertkit-react)
> Email Collection

- src/components/common/CharCounter/CharCounter.tsx
- src/components/pages/GameContainer/Game/Pregame.tsx
- Update CarCounter to count down from max to 0
- Add CharCounter to Pregame edit name form
> Update CarCounter to count down from max to 0. Add CharCounter to Pregame edit name form.

- src/components/pages/GameContainer/Game/Lobby.tsx
- src/components/pages/GameContainer/Game/Postgame.tsx
- Add condition to disable Join Lobby button if lobby code isn't 4 characters
- Remove console log.
> Disable Join Lobby button when code input isn't filled

- src/components/common/Footer/Footer.tsx
- src/components/pages/GameContainer/Game/Lobby.tsx
- src/components/pages/GameContainer/Game/Pregame.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- src/styles/components/common/footer.scss
- src/styles/general.scss
Footer and error styles complete.
> errors styled. footer styled.

- README.md
- src/components/common/SetHost/SetHost.tsx
- src/components/pages/GameContainer/Game/Finale/Finale.tsx
- src/components/pages/GameContainer/Game/Finale/index.ts
- src/components/pages/GameContainer/Game/Guessing/Guess.tsx
- src/components/pages/GameContainer/Game/Guessing/Guessing.tsx
- src/components/pages/GameContainer/Game/Guessing/index.ts
- src/components/pages/GameContainer/Game/Lobby/Lobby.tsx
- src/components/pages/GameContainer/Game/Lobby/index.ts
- src/components/pages/GameContainer/Game/Postgame/DefinitionResult.tsx
- src/components/pages/GameContainer/Game/Postgame/Postgame.tsx
- src/components/pages/GameContainer/Game/Postgame/index.ts
- src/components/pages/GameContainer/Game/Pregame/Pregame.tsx
- src/components/pages/GameContainer/Game/Pregame/WordChoice.tsx
- src/components/pages/GameContainer/Game/Pregame/index.ts
- src/components/pages/GameContainer/Game/Writing/Writing.tsx
- src/components/pages/GameContainer/Game/Writing/index.ts
- src/components/pages/GameContainer/Game/index.ts
- src/components/pages/GameContainer/GameContainer.tsx
- src/types/gameTypes.ts
- src/utils/helpers/gameHelpers.ts
- src/utils/localStorageInitialValues.ts
- Move Game components into respective directories
- Extract child components and props interfaces into respective files
- Extract functions from components into gameHelpers.ts
- Create localStorageInitialValues to keep consistent initial useLocalStorage values across files
- Add Product Hunt banner to README.md
> Refactor components, extract functions

- package.json
- src/components/common/TwitterButton/TwitterButton.tsx
- src/components/common/TwitterButton/index.ts
- src/components/pages/GameContainer/Game/Writing/Writing.tsx
- src/styles/components/common/twitterButton.scss
- src/styles/index.scss
- yarn.lock
----This adds a twitter share component----
> adds twitter sharability to defs

- src/components/common/Instructions/HostStepOne.tsx
- src/components/common/Instructions/HostStepThree.tsx
- src/components/common/Instructions/HostStepTwo.tsx
- src/components/common/Instructions/PlayerStepOne.tsx
- src/components/common/Instructions/PlayerStepThree.tsx
- src/components/common/Instructions/PlayerStepTwo.tsx
- src/components/pages/GameContainer/Game/Guessing/Guessing.tsx
- src/components/pages/GameContainer/Game/Lobby/Lobby.tsx
- src/components/pages/GameContainer/Game/Postgame/Postgame.tsx
- src/components/pages/GameContainer/Game/Pregame/Pregame.tsx
- src/styles/components/common/charCounter.scss
- src/styles/components/pages/lobby.scss
- src/styles/general.scss
- src/styles/globals.scss
- src/styles/mixins.scss
Fixed text alignment issues during guessing phase.
Refactored Lobby according to Figma.
> fixed alignment for word-display in guesses.tsx

- src/components/common/Expander/Expander.tsx
- src/components/common/Expander/index.ts
- src/components/common/Host/Host.tsx
- src/components/common/Player/Player.tsx
- src/components/pages/GameContainer/Game/Lobby/Lobby.tsx
- src/styles/components/common/expander.scss
- src/styles/index.scss
- src/types/commonTypes.ts
- Add Expander component
- Add styling for Expander
- Wrap instructions text in Lobby with Expander
> Add Expander container component and implement with instructions in Lobby component.

- src/components/common/Loader/Loader.tsx
- src/components/common/SetHost/SetHost.tsx
- src/components/pages/GameContainer/Game/Guessing/Guessing.tsx
- src/components/pages/GameContainer/Game/Lobby/Lobby.tsx
- src/components/pages/GameContainer/Game/Postgame/Postgame.tsx
- src/components/pages/GameContainer/Game/Pregame/Pregame.tsx
- src/components/pages/GameContainer/Game/Writing/Writing.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- src/state/index.ts
- src/state/isLoadingState.ts
- src/styles/components/common/loader.scss
- src/styles/index.scss
- Add Loader component
- Style Loader component
- Turn isLoading true and disable buttons on appropriate socket events
- Turn isLoading false on appropriate socket responses
- Disable appropriate buttons while isLoading true
- Disable custom word form 'Start Game' button while word form isn't filled
> Add Loader component, implement during loading phases, disable buttons during loading.

- src/components/common/ReactionPicker/ReactionPicker.tsx
- src/components/pages/GameContainer/Game/Postgame/DefinitionResult.tsx
- src/components/pages/GameContainer/Game/Postgame/Postgame.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- src/state/handleSendReactionFn.ts
- src/state/index.ts
- src/state/lobbyState.ts
- src/styles/components/common/reactionPicker.scss
- src/types/commonTypes.ts
- src/types/gameTypes.ts
- src/utils/helpers/gameHelpers.ts
- Add socket event listener 'get reaction'
- Add socket event emitter 'send reaction'
- Add handler and helper functions
- Add reactions property to lobbyData
- Add Recoil State
- Add types/interfaces
- Add animation/styling to ReactionPicker
- Add comments
> Update ReactionPicker to count times clicked by all players

- src/components/common/ProTip/ProTip.tsx
- src/components/pages/GameContainer/Game/Finale/Finale.tsx
- src/styles/components/common/charCounter.scss
- src/styles/general.scss
- src/types/gameTypes.ts
- src/utils/helpers/commonHelpers.ts
- src/utils/helpers/gameHelpers.ts
- src/utils/text/finaleText.json
- Add 'word' property to topThree interface and helper function
- Add JSON file for Finale text for users with no definition
- Add helper function to construct semi-random text
- Add commonHelpers file with getRandomFromArray function
- Use getRandomFromArray in ProTip
- Fix CharCounter, Modal styling bugs
> Add word and randomized text to Finale page

- src/components/common/Loader/Loader.tsx
- src/components/common/Modal/Modal.tsx
- src/components/common/SetHost/SetHost.tsx
- src/components/pages/GameContainer/Game/Guessing/Guessing.tsx
- src/components/pages/GameContainer/Game/Lobby/Lobby.tsx
- src/components/pages/GameContainer/Game/Postgame/Postgame.tsx
- src/components/pages/GameContainer/Game/Pregame/Pregame.tsx
- src/components/pages/GameContainer/Game/Writing/Writing.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- src/state/index.ts
- src/state/isLoadingState.ts
- src/state/loadingState.ts
- src/utils/constants.ts
- Update loadingState (was isLoadingState) to allow for more states
- Add optional zIndex prop to Modal to prioritize Modals
- Add constant/.env variable MAX_LOADING_TIME
> Update Loader to time out after a number of seconds and display a Modal on failure to load

- src/components/common/Expander/README.md
- src/components/common/Footer/README.md
- src/components/common/Header/README.md
- src/components/pages/GameContainer/GameContainer.tsx
- src/utils/helpers/errorCode.json
- src/utils/helpers/gameHelpers.ts
- Add handleReload to set loading status to 'ok' and reload page on loading timeout Modal
- Add 'value' check to if-statement in addReaction to prevent app crashing if value is 'null'
- Add READMEs to components
> Update game creation/loading logic to fix issue with creating an invalid game.

- src/components/pages/GameContainer/Game/Postgame/Postgame.tsx
- src/components/pages/GameContainer/Game/Postgame/RoundResults.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- Extract round-results divs into new RoundResults component
- Add sections for no votes, votes, and real definition in RoundResults
- Move new Host Modal from Postgame to GameContainer
- Add comments
> Honorable Mentions section

- src/components/common/ReactionPicker/ReactionButton.tsx
- src/components/common/ReactionPicker/ReactionPicker.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- src/state/gameState.ts
- src/types/gameTypes.ts
- src/utils/helpers/gameHelpers.ts
- Extract reaction button to ReactionButton component
- Add 100ms timeout to ReactionButton clicks
- Fix updateReactionCounts/interface to match API changes
- Set up Recoil state for ReactionButton timeout
> Add limits to ReactionButton to slow requests

- src/components/pages/GameContainer/Game/Lobby/Lobby.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- src/state/gameState.ts
- add boolean to trigger url join only after a token update
- add console logs for handleLogin, comment-out pulse check for testing
> Change URL joining to trigger only after login

- src/components/common/View/README.md
- src/components/common/View/View.tsx
- src/components/common/View/index.ts
- src/components/common/index.ts
- src/components/pages/GameContainer/Game/Finale/Finale.tsx
- src/components/pages/GameContainer/Game/Guessing/Guessing.tsx
- src/components/pages/GameContainer/Game/Postgame/Postgame.tsx
- src/components/pages/GameContainer/Game/Pregame/Pregame.tsx
- src/components/pages/GameContainer/Game/Writing/Writing.tsx
- create View component
- refactor conditional blocks in Game phase components
> Refactor conditional rendering blocks with View component for better JSX organization

- src/components/pages/GameContainer/GameContainer.tsx
- src/styles/components/common/header.scss
- src/styles/components/common/proTip.scss
- src/styles/components/pages/lobby.scss
This is PR is just for a quick change on a file to remove the console logging of lobby data.
> Removed the console logging of lobby data

- src/components/pages/GameContainer/Game/Pregame/AlphaBotSettings.tsx
Added a way to get the botlist dynamically from an API, rather than it being hard-coded.
> Added botlist to be gathered from API

- src/components/pages/GameContainer/Game/Lobby/Lobby.tsx
> aws text complete

- src/components/common/Modal/Modal.tsx
- src/components/common/ProTip/ProTip.tsx
- src/components/common/Scoreboard/Scoreboard.tsx
- src/components/pages/GameContainer/Game/Guessing/Guess.tsx
- src/components/pages/GameContainer/Game/Writing/BotSubmission.tsx
- src/components/pages/GameContainer/Game/Writing/Writing.tsx
- src/components/pages/GameContainer/GameContainer.tsx
- src/styles/components/common/modal.scss
- src/styles/components/common/proTip.scss
- src/styles/components/common/scoreboard.scss
- src/styles/components/pages/gameContainer.scss
- src/styles/components/pages/lobby.scss
- Fixed an issue where the bot would do double submission
- Added a way to retry should the bot API call would fail for submission
- Added a way to retry should the bot API call would fail for when guessing
- Made the scoreboard full screen
- Made the scores button more prominent
- Made adjustments for mobile to improve responsive design
- Removed the Pro-Tips
- Moved the header back to the left side.
- During the reveal phase, the scoreboard will automatically popup for all users
> Fixed bot double submission and made UI changes

- src/components/pages/GameContainer/Game/Pregame/AlphaBotSettings.tsx
This PR is to fix an issue with the botlist having an infinite loop and making over 20 calls per second.
> Fix botlist call infinite loop
